---
AllowPanicMode: False # use expired cached keys if server's offline and key expired?
TTL: 300 # for how long in seconds is a cached key valid before a new lookup is performed?
Permissions:
  all: # this literally means davidpelaez can access ANY account that ssh accepts at login
    - davidpelaez
  git: # this means gh user 'johndoe' can only login as git
    - johndoe